### ISSUE TITLE
Which meeting is BOSH summarized? Meeting notes?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/pmc-notes#26]
Firstly, thanks for making the PMC notes available (only just found them whilst treasure hunting thru github.com/cloudfoundry repos).

Which meeting are BOSH-related projects/status summarized? Can those meeting notes be included here? (or are they in a different repo/elsewhere)?

**Comment by dieucao** [comment]
@drnic I believe due to lack of participation @cppforlife no longer holds regular BOSH PMC meeting notes and just shares updates at the monthly CAB call.
